### PRODUCTS INDEX
GET http://localhost:3000/products

### PRODUCTS CREATE
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Test name",
  "price": 32,
  "image_url": "test image url",
  "description": "test description"
}

### PRODUCTS SHOW
GET http://localhost:3000/products/2

### PRODUCTS UPDATE
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
  "inventory": 15
}

### PRODUCTS DESTROY
DELETE http://localhost:3000/products/8