### PRODUCTS INDEX
GET http://localhost:3000/products

### PRODUCTS CREATE
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "carzzz",
  "price": 3200,
  "image_url": "car.com",
  "description": "you sit in the car",
  "supplier_id": 1
}

### PRODUCTS SHOW
GET http://localhost:3000/products/2

### PRODUCTS UPDATE
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
  "inventory": 15
}

### PRODUCTS DESTROY
DELETE http://localhost:3000/products/6

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Ace",
  "email": "ace@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "cheddar@gmail.com",
  "password": "password"
}

### Orders INDEX
GET http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzEzOTMwNDN9.8ITta5l6RpgXyUACq_dWSZfUykxFM6UibJmHdCDpSow

### Orders create
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzEzOTE3MTB9.5X87c-C6NMUz8HZt91eu_EWCFJogPQqSGVZIlErqBVg

{
  "product_id": 6,
  "quantity": 1
}

### Orders SHOW
GET http://localhost:3000/orders/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzEzOTE3MTB9.5X87c-C6NMUz8HZt91eu_EWCFJogPQqSGVZIlErqBVg